import jwt from 'jsonwebtoken';
import bcrypt from 'bcrypt';
import { AthleteRepository } from '../../domain/athlete/AthleteRepository';
import { ConflictError } from '../../domain/shared/DomainError';

export interface RegisterInput {
  firstname: string;
  lastname: string;
  username: string;
  email: string;
  password: string;
}

export interface RegisterOutput {
  token: string;
  user: {
    id: number;
    email: string;
    role: 'admin' | 'user';
    firstname: string;
    lastname: string;
  };
}

export class RegisterUseCase {
  constructor(private readonly athleteRepo: AthleteRepository) {}

  async execute(input: RegisterInput): Promise<RegisterOutput> {
    // Normalize inputs (email lowercase, trim whitespace)
    const email = input.email.trim().toLowerCase();
    const username = input.username.trim();

    // Check duplicates in parallel
    const [existingByEmail, existingByUsername] = await Promise.all([
      this.athleteRepo.findByEmail(email),
      this.athleteRepo.findByUsername(username),
    ]);

    if (existingByEmail) {
      throw new ConflictError('Ya existe una cuenta con este email');
    }
    if (existingByUsername) {
      throw new ConflictError('Este nombre de usuario ya está en uso');
    }

    // Hash password (10 rounds, same as login flow)
    const passwordHash = await bcrypt.hash(input.password, 10);

    // Persist (id is generated by athletes_local_id_seq in the repository)
    const athlete = await this.athleteRepo.create({
      firstname: input.firstname.trim(),
      lastname: input.lastname.trim(),
      username,
      email,
      passwordHash,
      role: 'user',
    });

    // Auto-login: sign JWT with same shape as LoginUseCase
    const secret = process.env.JWT_SECRET;
    if (!secret) throw new Error('JWT_SECRET not configured');

    const token = jwt.sign(
      { sub: athlete.id, email: athlete.email, role: athlete.role, firstname: athlete.firstname },
      secret,
      { expiresIn: '8h' }
    );

    return {
      token,
      user: {
        id: athlete.id,
        email: athlete.email,
        role: athlete.role,
        firstname: athlete.firstname,
        lastname: athlete.lastname,
      },
    };
  }
}
